/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg16w46;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author mani
 */
public class Table extends javax.swing.JFrame {

    private JScrollPane scr;
    private final JTable tabCheck;
    private DefaultTableModel dtb;

    /**
     * Creates new form Table
     */
    public Table() {

        dtb = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return 0==column;
            }
            
        };
        
        dtb.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                System.out.println("changed");
            }
        });
        
        tabCheck = new JTable();
        scr = new JScrollPane();
        scr.setViewportView(tabCheck);
        tabCheck.setFillsViewportHeight(true);
        initComponents();

        setDefVal();
    }

    private void setDefVal() {
        this.getContentPane().add(scr, BorderLayout.CENTER);

        dtb.addColumn("Check");
        dtb.addColumn("Name");
        dtb.addColumn("Val");

        dtb.addRow(new Object[]{Boolean.TRUE, "mani", "1"});
        dtb.addRow(new Object[]{Boolean.TRUE, "kani", "2"});
        dtb.addRow(new Object[]{Boolean.FALSE, "vani", "3"});
        dtb.addRow(new Object[]{Boolean.TRUE, "pani", "4"});
        dtb.addRow(new Object[]{Boolean.TRUE, "sani", "5"});

        tabCheck.setModel(dtb);
        TableColumn column = tabCheck.getColumnModel().getColumn(0);
        column.setCellRenderer(tabCheck.getDefaultRenderer(Boolean.class));
        column.setCellEditor(tabCheck.getDefaultEditor(Boolean.class));
        column.setMinWidth(10);
        column.setPreferredWidth(10);
        //tabCheck.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        this.pack();
        JButton jButton = new JButton("print");
        
        this.getContentPane().add(jButton, BorderLayout.NORTH);
        
        jButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    
                    MessageFormat header=new MessageFormat("Page #{0,number,integer}");
                    
                            
                    tabCheck.print(JTable.PrintMode.FIT_WIDTH,header,null);
                } catch (PrinterException ex) {
                    Logger.getLogger(Table.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
